# Pandas - 
- Open Sources Package 
- Pandas means Panal(Spreadsheet) Dataset(information).
- Using Pandas we can Load data, Data manupulation, Data Visualization and Data Analysis .

In [1]:
import numpy as np
import pandas as pd

In [28]:
dict1 = {'Name':['Rohan','Manav','Amar','Pawan'],
         'Mark':[56,78,34,77],
         'City':['Indore','Mumbai','Sagar','Bina']
         }

df = pd.DataFrame(dict1)
print(df)

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai
2   Amar    34   Sagar
3  Pawan    77    Bina

In [5]:
df.to_csv('friends.csv',index = False)   # convert into csv or excel foormat. , index = false ye index noumber ko hata dega.

In [6]:
df.head(2)  # Top 2 rows.

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai

In [7]:
df.tail(2)    # Botom 2 rows.

    Name  Mark   City
2   Amar    34  Sagar
3  Pawan    77   Bina

In [8]:
df.describe()   # describe all the information .

           Mark
count   4.00000
mean   61.25000
std    20.80665
min    34.00000
25%    50.50000
50%    66.50000
75%    77.25000
max    78.00000

In [ ]:
harsh = pd.read_csv('D:\Excel folder\employee_data_DEELETE.csv')  # to import csv file It work on jupeter notebook.

harsh

In [27]:
dict1['Mark'][1] = 66

df

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai
2   Amar    34   Sagar
3  Pawan    77    Bina