# What is pandas - 

- It leveraged the power and speed of Numpy to make data analysis and processing Easy for data science.
- It provide rich and highly robot data operation.
- It has function for analyzing, cleaning, exploring and mainpulating .
- The name 'Pandas' has a reference to both "Panel Data" & "Data Analysis" .


- excel kyu nahi kyuki python ke threw provide function , ML techonologies and many more.
  agar program ke andar data ayega to excel se bahut jada difficulties ho sakti hai isliyee...

- Ye numpy ki power or speed ka use karta hai for esay and fast processing .

## Pandas has tow types of data structures - 
1. Series - It's a one dimensional array with indexes it store a single column or row of data in a Dataframe.
(matlab ak row ya column me bass akk hi type ka data save ho sakta hai.) ,1 dimentional array(labeled)

2. DataFrame - Its tabular spreadshe like structure representing row each of which contain one or more multiple columns.2 dimentional data(labeled)
(diffrent type of data hold karne me capable hota hai..)

### Press tab for automatic show other functions.

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {'Name':['Rohan','Manav','Amar','Pawan'],
         'Mark':[56,78,34,77],
         'City':['Indore','Mumbai','Sagar','Bina']}

df = pd.DataFrame(dict1)

df

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai
2   Amar    34   Sagar
3  Pawan    77    Bina

In [3]:
df.to_csv('harsh_dele.csv')

In [7]:
df.to_csv('harsh_dele.csv', index = False)

In [9]:
df.head(2)  # Print top 2 row.

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai

In [11]:
df.tail(2)      #Print bottom 2 row.

    Name  Mark   City
2   Amar    34  Sagar
3  Pawan    77   Bina

In [13]:
df.describe()   # describe all the things.

           Mark
count   4.00000
mean   61.25000
std    20.80665
min    34.00000
25%    50.50000
50%    66.50000
75%    77.25000
max    78.00000

In [18]:
harsh = pd.read_csv('harsh_dele.csv')

In [20]:
harsh

    Name  Mark    City
0  Rohan    56  Indore
1  Manav    78  Mumbai
2   Amar    34   Sagar
3  Pawan    77    Bina

In [ ]:
harsh['department'][2]

In [ ]:
harsh['department'][3] = 'Science'   # for change values.

In [ ]:
harsh.to_csv('harsh_dele.csv')  # to save changes in csv file .

In [ ]:
harsh.index = ['frist','second','thired']  # when we have only few data .

## --------- Series & DataFrame------------

In [ ]:
ser = pd.Series(np.random.rand(34))

In [ ]:
ser     # right side float value numpy ke karan aa raahi hai..jo ki 0 se 1 tk hoti hai .
#type(ser)

In [50]:
new_df = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))
#                            ^                     ye column ke roop me print karega.
#                            |
                #  [[0.12, 0.45, 0.78, 0.33, 0.91],
                #  [0.55, 0.67, 0.22, 0.88, 0.14],
                #  ...
                # ]

new_df
# new_df.head(5)
# new_df.tail(5)
# new_df.describe()
# new_df.dtypes

            0         1         2         3         4
0    0.045046  0.498339  0.577781  0.882425  0.600278
1    0.284933  0.843416  0.782477  0.479288  0.729887
2    0.581012  0.221741  0.444812  0.122139  0.881964
3    0.426907  0.464778  0.009708  0.343575  0.724708
4    0.353219  0.736915  0.587464  0.215597  0.600299
..        ...       ...       ...       ...       ...
329  0.555177  0.425232  0.855065  0.766500  0.894799
330  0.835135  0.855443  0.698347  0.259536  0.312863
331  0.577542  0.670448  0.845926  0.878744  0.078552
332  0.182264  0.988353  0.642026  0.700670  0.648012
333  0.460559  0.238602  0.081649  0.252321  0.211790

[334 rows x 5 columns]

In [52]:
new_df[0][0] = 'harsh'


new_df.dtypes

C:\Users\Harsh\AppData\Local\Temp\ipykernel_24744\3443123043.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_df[0][0] = 'harsh'
C:\Users\Harsh\AppData\Local\Temp\ipykernel_24744\3443123043.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harsh' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  new_df[0][0] = 'harsh'

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [54]:
new_df

            0         1         2         3         4
0       harsh  0.498339  0.577781  0.882425  0.600278
1    0.284933  0.843416  0.782477  0.479288  0.729887
2    0.581012  0.221741  0.444812  0.122139  0.881964
3    0.426907  0.464778  0.009708  0.343575  0.724708
4    0.353219  0.736915  0.587464  0.215597  0.600299
..        ...       ...       ...       ...       ...
329  0.555177  0.425232  0.855065  0.766500  0.894799
330  0.835135  0.855443  0.698347  0.259536  0.312863
331  0.577542  0.670448  0.845926  0.878744  0.078552
332  0.182264  0.988353  0.642026  0.700670  0.648012
333  0.460559  0.238602  0.081649  0.252321  0.211790

[334 rows x 5 columns]

In [56]:
new_df.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [58]:
new_df.columns

RangeIndex(start=0, stop=5, step=1)

In [60]:
new_df[0][0] = 0.32554

In [62]:
new_df.to_numpy()   # When we want to convert into numpy.

array([[0.32554, 0.49833865701806856, 0.577781451206111,
        0.8824245197149208, 0.6002775724434801],
       [0.2849331761037427, 0.8434156635569093, 0.7824765238010745,
        0.47928788628119623, 0.7298869011795108],
       [0.5810124475707833, 0.2217407765621615, 0.44481240506125885,
        0.12213903504888546, 0.8819643884456058],
       ...,
       [0.5775423185374862, 0.6704484565349658, 0.8459262015050036,
        0.8787435418811782, 0.0785524077535037],
       [0.18226383895548193, 0.9883531884256719, 0.6420263751760695,
        0.7006696658203214, 0.6480122910340717],
       [0.4605593572561698, 0.23860231253154218, 0.08164911468020142,
        0.2523205779108987, 0.21179027837687547]], dtype=object)

In [64]:
# when we want to convert row into column .

new_df.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.32554,0.284933,0.581012,0.426907,0.353219,0.244256,0.899506,0.816867,0.367343,0.297264,...,0.72226,0.743382,0.913953,0.474419,0.376514,0.555177,0.835135,0.577542,0.182264,0.460559
1,0.498339,0.843416,0.221741,0.464778,0.736915,0.094039,0.485926,0.348973,0.197395,0.605167,...,0.977902,0.572213,0.724666,0.683193,0.173348,0.425232,0.855443,0.670448,0.988353,0.238602
2,0.577781,0.782477,0.444812,0.009708,0.587464,0.316048,0.374755,0.397454,0.40045,0.053058,...,0.62519,0.755614,0.173239,0.952416,0.794921,0.855065,0.698347,0.845926,0.642026,0.081649
3,0.882425,0.479288,0.122139,0.343575,0.215597,0.075743,0.346085,0.413175,0.318847,0.995361,...,0.528131,0.096728,0.50824,0.553278,0.743547,0.7665,0.259536,0.878744,0.70067,0.252321
4,0.600278,0.729887,0.881964,0.724708,0.600299,0.909256,0.098427,0.369978,0.32839,0.17051,...,0.431807,0.521728,0.97407,0.876492,0.761981,0.894799,0.312863,0.078552,0.648012,0.21179

In [66]:
new_df.head(5)

          0         1         2         3         4
0   0.32554  0.498339  0.577781  0.882425  0.600278
1  0.284933  0.843416  0.782477  0.479288  0.729887
2  0.581012  0.221741  0.444812  0.122139  0.881964
3  0.426907  0.464778  0.009708  0.343575  0.724708
4  0.353219  0.736915  0.587464  0.215597  0.600299

In [68]:
# When want to short upside down.

new_df.sort_index( axis = 0 , ascending = False )  # axis = rows

            0         1         2         3         4
333  0.460559  0.238602  0.081649  0.252321  0.211790
332  0.182264  0.988353  0.642026  0.700670  0.648012
331  0.577542  0.670448  0.845926  0.878744  0.078552
330  0.835135  0.855443  0.698347  0.259536  0.312863
329  0.555177  0.425232  0.855065  0.766500  0.894799
..        ...       ...       ...       ...       ...
4    0.353219  0.736915  0.587464  0.215597  0.600299
3    0.426907  0.464778  0.009708  0.343575  0.724708
2    0.581012  0.221741  0.444812  0.122139  0.881964
1    0.284933  0.843416  0.782477  0.479288  0.729887
0     0.32554  0.498339  0.577781  0.882425  0.600278

[334 rows x 5 columns]

In [70]:
# When want to short columns.

new_df.sort_index( axis = 1 , ascending = False )  # axis = column

            4         3         2         1         0
0    0.600278  0.882425  0.577781  0.498339   0.32554
1    0.729887  0.479288  0.782477  0.843416  0.284933
2    0.881964  0.122139  0.444812  0.221741  0.581012
3    0.724708  0.343575  0.009708  0.464778  0.426907
4    0.600299  0.215597  0.587464  0.736915  0.353219
..        ...       ...       ...       ...       ...
329  0.894799  0.766500  0.855065  0.425232  0.555177
330  0.312863  0.259536  0.698347  0.855443  0.835135
331  0.078552  0.878744  0.845926  0.670448  0.577542
332  0.648012  0.700670  0.642026  0.988353  0.182264
333  0.211790  0.252321  0.081649  0.238602  0.460559

[334 rows x 5 columns]

In [72]:
new_df2 = new_df   # yaha new memory nahi legga yah bass ak view hai new_df ka

In [74]:
new_df2[0][3] = 999999

In [76]:
new_df

            0         1         2         3         4
0     0.32554  0.498339  0.577781  0.882425  0.600278
1    0.284933  0.843416  0.782477  0.479288  0.729887
2    0.581012  0.221741  0.444812  0.122139  0.881964
3      999999  0.464778  0.009708  0.343575  0.724708
4    0.353219  0.736915  0.587464  0.215597  0.600299
..        ...       ...       ...       ...       ...
329  0.555177  0.425232  0.855065  0.766500  0.894799
330  0.835135  0.855443  0.698347  0.259536  0.312863
331  0.577542  0.670448  0.845926  0.878744  0.078552
332  0.182264  0.988353  0.642026  0.700670  0.648012
333  0.460559  0.238602  0.081649  0.252321  0.211790

[334 rows x 5 columns]

In [78]:
new_df2 = new_df.copy()  # for copy .

In [80]:
new_df.loc[0,0] = 67458555   #  lock vvalues karne me bhi kaam aata kyuki kabhi kabhi paanda isko kaaha view
                            # return hoga kaha copy to isliye bhi kaam aata hai.

In [82]:
new_df.head(6)

          0         1         2         3         4
0  67458555  0.498339  0.577781  0.882425  0.600278
1  0.284933  0.843416  0.782477  0.479288  0.729887
2  0.581012  0.221741  0.444812  0.122139  0.881964
3    999999  0.464778  0.009708  0.343575  0.724708
4  0.353219  0.736915  0.587464  0.215597  0.600299
5  0.244256  0.094039  0.316048  0.075743  0.909256

In [84]:
new_df.columns = list('ABCDE')  # to change column name

# new_df.loc[0,0] = 674584    ab a likhana padega 2nd 0 ki plase prr.

In [86]:
new_df

            A         B         C         D         E
0    67458555  0.498339  0.577781  0.882425  0.600278
1    0.284933  0.843416  0.782477  0.479288  0.729887
2    0.581012  0.221741  0.444812  0.122139  0.881964
3      999999  0.464778  0.009708  0.343575  0.724708
4    0.353219  0.736915  0.587464  0.215597  0.600299
..        ...       ...       ...       ...       ...
329  0.555177  0.425232  0.855065  0.766500  0.894799
330  0.835135  0.855443  0.698347  0.259536  0.312863
331  0.577542  0.670448  0.845926  0.878744  0.078552
332  0.182264  0.988353  0.642026  0.700670  0.648012
333  0.460559  0.238602  0.081649  0.252321  0.211790

[334 rows x 5 columns]

In [88]:
new_df.drop(0,axis = 1) # To remove unnessary column. [1 means coolumn ] 

# drop(0,axis = 1 ) means column hata do jisme 0 ho .

KeyError: '[0] not found in axis'

In [ ]:
new_df

In [ ]:
new_df.drop(['C','D'],axis = 1)
                                        # but not chhangge  actual vvalue .
new_df.drop([2] , axis =0)

In [ ]:
# new_df3 =  new_df.drop([2] , axis =0) # If we want to ssave changges [ kkarna nahia hai ] exaample  liy tha .

In [ ]:
# new_df.drop([2] , axis =0 , inplace = True)  yye dusara tarika hai . yee origanal ko modify krr dega.

In [ ]:
new_df.reset_index() # reset index value like 0,1,2,3,4,5,6,7....

In [ ]:
new_df.reset_index(drop = True ,  inplace =True )  # remove drop = True unwanted column 
                                                    #  inplace = True  modifyyyy...

In [ ]:
new_df

In [ ]:
# Go to Google how to remove null values from pandas.

## hamesa loc.[] ya iloc.[] hi use karna hai kisi bhi operation ko pperform karne ke liye kyuki panda kab view return kare or kab actual value change kre de ye nahi pata rahta  hai .

In [96]:
new_df.loc[[1,2],['C','D']]    # When we want to only specific row and column.

# loc = location based indexing .

          C         D
1  0.782477  0.479288
2  0.444812  0.122139

In [ ]:
new_df.loc[:,['C','D']]  # when we want all C,D rows.

In [ ]:
new_df.loc[[1,2] , :]  # When we want to all columns OF 1 & 2.

In [ ]:
new_df.loc[(new_df['A'] < 0.3 )] #

In [ ]:
new_df.loc[(new_df['A'] < 0.3 ) & (new_df['C'] > 0.2) ] # It doesn't change actual value.

## iloc - We can fetch value with the help of index number and column number (no need to give name of column ) or remember the name of row and column .
like (2,A) ye nahi chalega .

In [ ]:
new_df

In [ ]:
new_df.iloc[0,4]

In [ ]:
new_df.iloc[[0,1] , [2,3] ]

## Go on a google and search it how to remove duplicate,nulls,... values in panda library.

In [ ]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df

In [ ]:
df.drop_duplicates()

# df.drop_duplicates(subset=['name'])  # name column se duplicate hata dega .
# df.drop_duplicates(subset=['name'],keep = Frist)
# df.drop_duplicates(subset=['name'],keep = Last)
# df.drop_duplicates(subset=['name'],keep = False)

In [100]:
>>> dff = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
...                             pd.NaT]})
>>> dff

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [102]:
dff.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [104]:
>>> dff = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
...                    "toy": [np.nan,np.nan,np.nan,],
...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
...                             pd.NaT]})
>>> dff

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [106]:
dff.dropna(how = 'all',axis = 1) #

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [ ]:
dff['name'].value_counts(dropna = False)

In [ ]:
dff.info()

In [ ]:
dff.notnull()  # jaha khali hoga waha false return karega .
# .isnull()

#### Create a data frame which contain only integer with 3 rows and 2 columns run following data frame methods on them:
- df.describe()
- df.mean()
- df.corr()
- df.count()         # these are statics methods .
- df.max()
- df.min()
- df.median()
- df.std()

In [ ]:
nw_df = pd.DataFrame({'Column1': [1,2,3],
                     'Column2':[4,5,6]})

In [ ]:
nw_df

In [ ]:
nw_df.mean()

### Search on Google pandas read excel.

In [ ]:
!pip install xlrd

In [ ]:
!pip install xlrd

In [ ]:
data = pd.read_excel('for_df_pands.xlsx', sheet_name = 'sheet2')

In [ ]:
data.iloc[0][0] = 98

In [ ]:
!pip install openpyxl

In [ ]:
data.to_excel('for_df_pands.xlsx', sheet_name = 'sheet2') # to change in excel .