In [1]:
import pandas as pd
import numpy as np

In [2]:
Emp_df = pd.read_csv(r'D:\AI & ML\Libraries\Sir\Pandas\Practice_dataset\Emp_attrition_csv.csv')
Emp_df

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89.0,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21.0,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74.0,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50.0,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68.0,No,No,No,Fair,Medium,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74605,13450,44,Female,20,Healthcare,7578,Fair,Medium,Low,2,...,3,Mid,Large,52.0,No,No,No,Fair,Very High,Left
74606,2386,45,Male,26,Technology,8342,Excellent,Very High,Below Average,3,...,4,Mid,Medium,NaN,Yes,No,No,Poor,High,Stayed
74607,36968,28,Female,3,Technology,9763,Poor,Low,Average,0,...,3,Senior,Small,67.0,No,No,No,Poor,Medium,Left
74608,24276,37,Male,3,Education,3644,Fair,High,Average,2,...,4,Entry,Medium,16.0,No,No,No,Excellent,Medium,Stayed
74609,9839,38,Male,28,Media,6172,Good,High,High,0,...,2,Mid,Medium,84.0,No,No,No,Excellent,Low,Stayed

# EDA

In [3]:
Emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74610 entries, 0 to 74609
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 74610 non-null  int64
 1   Age                         74610 non-null  int64
 2   Gender                      74610 non-null  object
 3   Years at Company            74610 non-null  int64
 4   Job Role                    74610 non-null  object
 5   Monthly Income              74610 non-null  int64
 6   Work-Life Balance           74610 non-null  object
 7   Job Satisfaction            74610 non-null  object
 8   Performance Rating          74610 non-null  object
 9   Number of Promotions        74610 non-null  int64
 10  Overtime                    74610 non-null  object
 11  Distance from Home          72698 non-null  float64
 12  Education Level             74610 non-null  object
 13  Marital Status              74610 non-null  object
 14  Number of Dependents        74610 non-null  int64
 15  Job Level                   74610 non-null  object
 16  Company Size                74610 non-null  object
 17  Company Tenure (In Months)  72197 non-null  float64
 18  Remote Work                 74610 non-null  object
 19  Leadership Opportunities    74610 non-null  object
 20  Innovation Opportunities    74610 non-null  object
 21  Company Reputation          74610 non-null  object
 22  Employee Recognition        74610 non-null  object
 23  Attrition                   74610 non-null  object
dtypes: float64(2), int64(6), object(16)
memory usage: 13.7+ MB

In [4]:
Emp_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Employee ID,74610.0,37246.028696,21505.785344,1.0,18624.25,37239.5,55871.75,74498.0
Age,74610.0,38.529379,12.082299,18.0,28.00,39.0,49.00,59.0
Years at Company,74610.0,15.722638,11.224059,1.0,7.00,13.0,23.00,51.0
Monthly Income,74610.0,7344.931417,2596.373589,1226.0,5652.00,7348.5,8876.00,50030.0
Number of Promotions,74610.0,0.832958,0.995326,0.0,0.00,1.0,2.00,4.0
Distance from Home,72698.0,49.990839,28.519135,1.0,25.00,50.0,75.00,99.0
Number of Dependents,74610.0,1.657432,1.579862,0.0,0.00,1.0,3.00,15.0
Company Tenure (In Months),72197.0,55.711899,25.392325,2.0,36.00,56.0,76.00,128.0

In [5]:
Emp_df.isnull().sum()

Employee ID                      0
Age                              0
Gender                           0
Years at Company                 0
Job Role                         0
Monthly Income                   0
Work-Life Balance                0
Job Satisfaction                 0
Performance Rating               0
Number of Promotions             0
Overtime                         0
Distance from Home            1912
Education Level                  0
Marital Status                   0
Number of Dependents             0
Job Level                        0
Company Size                     0
Company Tenure (In Months)    2413
Remote Work                      0
Leadership Opportunities         0
Innovation Opportunities         0
Company Reputation               0
Employee Recognition             0
Attrition                        0
dtype: int64

In [6]:
Emp_df.dtypes

Employee ID                     int64
Age                             int64
Gender                         object
Years at Company                int64
Job Role                       object
Monthly Income                  int64
Work-Life Balance              object
Job Satisfaction               object
Performance Rating             object
Number of Promotions            int64
Overtime                       object
Distance from Home            float64
Education Level                object
Marital Status                 object
Number of Dependents            int64
Job Level                      object
Company Size                   object
Company Tenure (In Months)    float64
Remote Work                    object
Leadership Opportunities       object
Innovation Opportunities       object
Company Reputation             object
Employee Recognition           object
Attrition                      object
dtype: object

In [7]:
Emp_df.columns

Index(['Employee ID', 'Age', 'Gender', 'Years at Company', 'Job Role',
       'Monthly Income', 'Work-Life Balance', 'Job Satisfaction',
       'Performance Rating', 'Number of Promotions', 'Overtime',
       'Distance from Home', 'Education Level', 'Marital Status',
       'Number of Dependents', 'Job Level', 'Company Size',
       'Company Tenure (In Months)', 'Remote Work', 'Leadership Opportunities',
       'Innovation Opportunities', 'Company Reputation',
       'Employee Recognition', 'Attrition'],
      dtype='object')

In [8]:
Emp_df['Distance from Home'] = Emp_df['Distance from Home'].fillna(Emp_df['Distance from Home'].mean())
Emp_df['Distance from Home'].isnull().sum()

0

In [9]:
Emp_df.isnull().sum()

Employee ID                      0
Age                              0
Gender                           0
Years at Company                 0
Job Role                         0
Monthly Income                   0
Work-Life Balance                0
Job Satisfaction                 0
Performance Rating               0
Number of Promotions             0
Overtime                         0
Distance from Home               0
Education Level                  0
Marital Status                   0
Number of Dependents             0
Job Level                        0
Company Size                     0
Company Tenure (In Months)    2413
Remote Work                      0
Leadership Opportunities         0
Innovation Opportunities         0
Company Reputation               0
Employee Recognition             0
Attrition                        0
dtype: int64

In [10]:
Emp_df['Company Tenure (In Months)'] = Emp_df['Company Tenure (In Months)'].fillna(Emp_df['Company Tenure (In Months)'].mean())
Emp_df['Company Tenure (In Months)'].isnull().sum()

0

In [11]:
Emp_df

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89.000000,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21.000000,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74.000000,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50.000000,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68.000000,No,No,No,Fair,Medium,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74605,13450,44,Female,20,Healthcare,7578,Fair,Medium,Low,2,...,3,Mid,Large,52.000000,No,No,No,Fair,Very High,Left
74606,2386,45,Male,26,Technology,8342,Excellent,Very High,Below Average,3,...,4,Mid,Medium,55.711899,Yes,No,No,Poor,High,Stayed
74607,36968,28,Female,3,Technology,9763,Poor,Low,Average,0,...,3,Senior,Small,67.000000,No,No,No,Poor,Medium,Left
74608,24276,37,Male,3,Education,3644,Fair,High,Average,2,...,4,Entry,Medium,16.000000,No,No,No,Excellent,Medium,Stayed
74609,9839,38,Male,28,Media,6172,Good,High,High,0,...,2,Mid,Medium,84.000000,No,No,No,Excellent,Low,Stayed

In [12]:
print(Emp_df.shape)
Emp_df.duplicated().sum()

(74610, 24)

112

In [13]:
Emp_df.drop_duplicates(inplace=True)
print(Emp_df.shape)

(74498, 24)

In [14]:
Emp_df.duplicated().sum()

0

In [15]:
Emp_df['Education Level'].unique()   # Ab ham 'Masterâ€™s Degree', 'Bachelorâ€™s Degree', in dono ko replace karenge.

array(['Associate Degree', 'Masterâ€™s Degree', 'Bachelorâ€™s Degree',
       'High School', 'PhD'], dtype=object)

In [17]:
Emp_df['Education Level'].map({'Associate Degree':"Associate Degree",
                               'Masterâ€™s Degree':'Master Degree', 
                               'Bachelorâ€™s Degree':'Bacheloras Degree',
                               'High School':'High School',"PhD":"PhD"})

0         Associate Degree
1            Master Degree
2        Bacheloras Degree
3              High School
4              High School
               ...
74493     Associate Degree
74494        Master Degree
74495     Associate Degree
74496    Bacheloras Degree
74497          High School
Name: Education Level, Length: 74498, dtype: object

In [18]:
Emp_df['Education Level'].isnull().sum()

0

In [20]:
Emp_df.replace({'Masterâ€™s Degree':'Master Degree', 
                               'Bachelorâ€™s Degree':'Bacheloras Degree',},inplace=True)

In [21]:
Emp_df['Education Level']

0         Associate Degree
1            Master Degree
2        Bacheloras Degree
3              High School
4              High School
               ...
74493     Associate Degree
74494        Master Degree
74495     Associate Degree
74496    Bacheloras Degree
74497          High School
Name: Education Level, Length: 74498, dtype: object